# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: Windows containers Internal Test Release
on:
  workflow_dispatch:

jobs:
  BuildAndUpload:
    uses: ./.github/workflows/test-build.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      ContainerRepositoryNameAndTag: "windows-container-internal:latest"
      BucketKey: "windows-container-internal"
      PackageBucketKey: "windows-container-internal"
